RUN apt-get update
RUN apt-get install -y bash

RUN npm install -g npm
RUN npm install -g yarn

SHELL [ "/bin/bash", "-c" ]

WORKDIR /xui/common

## Copy the configuration and install dependencies. This part does not change so often during development.
COPY package.json package.json
COPY yarn.lock yarn.lock
COPY .eslintignore .eslintignore
COPY .eslintrc.js .eslintrc.js
COPY tsconfig.json tsconfig.json

RUN yarn install --ignore-scripts --network-timeout 100000

# Copy the sources and assets which change often to image.
COPY assets assets
COPY src src

RUN yarn postinstall

# Make a command to keep the container running when started.
CMD ["tail", "-f", "/dev/null"]
