FROM alpine:3.17

RUN apk update && apk add bash

WORKDIR /tmp

RUN wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
RUN tar -xf node-v18.12.1-linux-x64.tar.xz --directory=/usr/local --strip-components=1
RUN rm node-v18.12.1-linux-x64.tar.xz

RUN apk add npm

SHELL [ "/bin/bash", "-c" ]

WORKDIR /xui/common

COPY package.json package.json
COPY .eslintignore .eslintignore
COPY .eslintrc.js .eslintrc.js
COPY tsconfig.json tsconfig.json

RUN npm install

COPY src src

RUN npm run postinstall
RUN npm run build

CMD ["tail", "-f", "/dev/null"]
