#!groovy

DOCKER_IMAGE_NAME='xui_common_gv_image'
DOCKER_CONTAINER_NAME='xui_common_gv'
JUNIT_TEST_REPORT_FILE_NAME='junit_common_testreport.xml'

checkTypesExecutionResultCode = -1 
packageSecurityAuditResultCode = -1
packageSecurityAuditNotAllowedBits = 248 
linterResultCode = -1

node {
    
        // if (env.BRANCH_NAME == 'master') {
        //     echo 'I only execute on the master branch'
        // } else {
        //     echo 'I execute elsewhere'
        // }
        
            stage("try1"){
                echo"Hello stage1"
            }

    
        stage('clean up') {
        containerExistsResultCode = bat (
            script: "docker container inspect ${DOCKER_CONTAINER_NAME}",
            returnStatus: true
        )
        // 'docker container inspect' return 0 if a container was found
        if (0 == containerExistsResultCode) {
            catchError {
                bat "docker stop ${DOCKER_CONTAINER_NAME}"
                bat "docker rm ${DOCKER_CONTAINER_NAME}"
            }
        }
    }

                stage("try2"){
                echo"Hello stage2"
            }
    
}
